- src/components/createElementComponent.js
- src/components/createElementComponent.test.js
Add the Element component's type as a static property. This will eventually be used in the Stripe.js core library to enable passing an Element component to `elements.getElement`.
```js
const cardElement = elements.getElement(CardElement);
```
I wrote a unit test.
> store Elements type on Element component

- examples/class-components/0-Card-Minimal.js
- examples/class-components/1-Card-Async.js
- examples/hooks/0-Card-Minimal.js
- examples/hooks/1-Card-Async.js
- examples/hooks/2-Card-Detailed.js
- examples/hooks/3-Split-Card.js
- examples/hooks/4-Payment-Request-Button.js
- examples/hooks/5-IBAN.js
- examples/hooks/6-iDEAL.js
- src/components/Elements.js
- src/components/createElementComponent.js
- src/index.js
Before Stripe.js loads, ElementsConsumer should be called with an object with null values rather with null. This better mirrors the useElements and useStripe hooks and it gets around this kind of awkwardness:
```js
const InjectedCheckoutForm = () => {
return (
<ElementsConsumer>
{(stuff) => (
<MyCheckoutForm elements={stuff && stuff.elements} stripe={stuff && stuff.stripe} />
)}
</ElementsConsumer>
);
};
```
https://github.com/stripe/react-stripe/tree/master/.github/API_REVIEW.md
Lots of example updates, existing tests
> move elements consumer null

- .eslintrc.yml
- examples/hooks/4-Payment-Request-Button.js
- src/components/createElementComponent.js
Poking around I noticed that `eslint-plugin-react-hooks` was already a dependency, but it wasn't enabled. This is an important plugin when using React Hooks as it prevents potentially undefined behavior.
This enables `eslint-plugin-react-hooks` making `rules-of-hooks` and error and `exhaustive-deps` a warning, and also fixes any existing violations uncovered.
* `yarn build` runs successfully
> Enable eslint-plugin-react-hooks, fix violations

- .eslintrc.yml
- src/components/Elements.js
- src/components/createElementComponent.js
The require-default-props lint rule was being overly restrictive for this use case. There is no good reason to include a value in `defaultProps` if it is truly optional, as that just means that React now has to do the work to merge this `undefined` value into props for no reason.
I'd argue that you should just avoid `defaultProps` all together and use destructuring with default values, but that's maybe more personal preference.
`yarn build` completes successfully
> Disable require-default-props lint rule

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- .storybook/example.stories.js
- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- docs/migrating.md
- package.json
Rename from React Stripe to React Stripe.js
> react-stripe -> react-stripe-js

- rollup.config.js
Fixes #11 
Rollup was inlining rather than requiring/importing PropTypes in the cjs and es builds.
I inspected and used the build output.
> remove inlined PropTypes for cjs and es builds

- README.md
Minor update to the minimal example, the event is called `event` and the button should have a type on it to be valid HTML and stop most linters from yelling at you.
> fix minimal example

- src/components/createElementComponent.js
- src/components/createElementComponent.test.js
- src/index.js
Update `createElementComponent` to create a shell component on the server.
The shell component does only the following:
* Ensure the Element component is being rendered inside an `Elements` provider.
* Render the Element's wrapper `div` with `className` and `id`.
Fixes #19 
I wrote unit tests and manually tested the fix with Next.js SSR.
> Render a shell Element component on the server

- README.md
Imports were defined incorrectly in the examples in the README.md causing errors without easy debugging. Definitely a trap for young players! 
Almost raised a ticket but instead here is a fixed PR 😄 . 
This is what I did to make it work in my app that uses the library 😆 .
> [Docs] Fixed imports in examples

- examples/class-components/0-Card-Minimal.js
- examples/class-components/1-Card-Detailed.js
- examples/class-components/2-Split-Card.js
- examples/class-components/3-Payment-Request-Button.js
- examples/class-components/4-IBAN.js
- examples/class-components/5-iDEAL.js
- examples/hooks/0-Card-Minimal.js
- examples/hooks/1-Card-Detailed.js
- examples/hooks/2-Split-Card.js
- examples/hooks/3-Payment-Request-Button.js
- examples/hooks/4-IBAN.js
- examples/hooks/5-iDEAL.js
Add the following clarification comment to examples:
> Make sure to call `loadStripe` outside of a component’s render to avoid recreating the `Stripe` object on every render.
> Add comment about loadStripe outside of render in examples

- src/components/Elements.js
Simple change to make debugging with React DevTools a little bit easier by having a non-generic displayName. 
In the devtools window the context component currently shows up as `<Context.Provdier>` this change would make it show up as `<Stripe.Provider>` With the generic name it can be a little annoying debugging if you have multiple providers all with the same generic displayName. 
**before**
**after**
If you're unfamiliar with the context displayName documentation is here: https://reactjs.org/docs/context.html#contextdisplayname
My real motivation for this is an issue with a project that has multiple generic named "Provider" components and I was tracking the following a warning down:
After a little bit of digging realized it was related to `react-stripe-elements` as it has a context …
> Add displayName property to context object for easier debugging with React Devtools

- package.json
- rollup.config.js
- src/components/Elements.test.js
- src/components/Elements.tsx
- src/components/createElementComponent.test.js
- src/components/createElementComponent.tsx
- src/types/index.ts
- src/utils/usePrevious.test.tsx
- test/setupJest.js
- tsconfig.json
TypeScript projects configured with `"esModuleInterop": false` fail to import our types, which contain import statements like
```
import React from 'react';
```
To properly resolve our types without `esModuleInterop` enabled, this should instead be
```
import * as React from 'react';
```
This PR updates our project to use the latter style, which results in emitted types also using that style.
> Fix types for TS projects not using esModuleInterop

- src/components/Elements.tsx
Don't use `React.createContext`
Avoid `import *` for non-type imports
Doesn't change the build output
> `import {createContext} from 'react'`

- package.json
- rollup.config.js
- scripts/check-imports
- src/components/Elements.test.js
- src/components/Elements.tsx
- src/components/createElementComponent.test.js
- src/components/createElementComponent.tsx
- test/setupJest.js
- tsconfig.json
Fix #33 
#31 used names exports for package "prop-types", which doesn't work when using this package as an ES Module. 
Partially reverts #31 to use default imports for packages that expect them, but make sure generated types don't use default import to preserve the intent of #31.
Verified in a test project the exported types are complete.
Added a test on generated type definitions to ensure we don't re-introduce default import for types in the future.
Check https://github.com/stripe/react-stripe-js/compare/v1.0.0-beta.4...hofman/fix-esmodule-interop to see the combined change with #31
> Fix ES Module interop

- package.json
- scripts/check-imports
- src/components/Elements.tsx
- src/components/createElementComponent.test.js
- src/components/createElementComponent.tsx
- src/types/index.ts
- src/utils/useCallbackReference.ts
- src/utils/usePrevious.test.tsx
- src/utils/usePrevious.ts
Fixes #38 
Only use default import for `react`
Use react types through `ReactType`
Added test to ensure no named imports are used for code (not types) since React and related are not ES Modules.
> Fix React named imports

- examples/class-components/6-FPX.js
- examples/hooks/6-FPX.js
- examples/styles/common.css
- package.json
- src/index.ts
- src/types/index.ts
- yarn.lock
* Add components and types for `auBankAccount` and `fpxBank` elements.
* Add an FPX example; no auBankAccount example for now since it is still in beta
I manually tested that both Elements wired up correctly.
> Fpx bank and au bank account elements

- rollup.config.js
Ensure that babel transpiles TypeScript files to ES5. 
Fixes #50
Investigated build output and tested locally.
> Force babel to transpile ts and tsx files

- rollup.config.js
Expand babel to transpile `js` and `jsx` in all rollup configs. Fix from #51
> add js and jsx to rollup configs

- .flowconfig
Not sure whether this will work for flow users, but since the `decls` folder has been renamed `types` it should probably be reflected here.
> chore: remove flow config

- package.json
- rollup.config.js
- src/components/Elements.tsx
- src/env.d.ts
- test/mocks.js
Registers the current package.json version with Stripe.js when a `Stripe` instance is first passed.
> Register package version with Stripe instance

- docs/migrating.md
I noticed the required client secret was missing on the migration examples.
> Include the required client secret in migrating.md

- .storybook/preview-head.html
I get the following error when bringing up storybook for this project.
`_VERSION is not defined`
Looks like storybook uses its own webpack config as opposed to the project's rollup config.
The fix is inspired by the way a global _VERSION=true was added to the jest config when _VERSION was introduced.
Storybook started working after adding this change.
> add preview-head.html with _VERSION to storybook

- .gitignore
- package.json
- src/components/Elements.test.tsx
- src/components/createElementComponent.tsx
- yarn.lock
This PR upgrades the `react` and `react-dom` development dependencies, and specifies that we now support React 17 in the `peerDependencies`.
React 17 [changes the timing of when effects are cleaned up](https://reactjs.org/blog/2020/08/10/react-v17-rc.html#effect-cleanup-timing). This caused one of our tests to break, since it was synchronsly asserting that `element.destroy` was called when an Element component was unmounted. To fix the test, I needed to upgrade our `@testing-library/react` dependency to at least [10.4.7](https://github.com/testing-library/react-testing-library/releases/tag/v10.4.7), which ensures that effects are flushed synchronously when `unmount` is called in a test. I also upgraded a few related deps, just to keep us up to date.
A different test failed due to the …
> Support React 17

- src/components/createElementComponent.test.tsx
- src/components/createElementComponent.tsx
https://github.com/stripe/react-stripe-js/issues/152 reported an issue where Elements are not destroyed after being unmounted, causing errors when attempting to remount an Element of the same type later.
The issue was introduced in https://github.com/stripe/react-stripe-js/pull/147. We close over the current Element ref in the effect cleanup function when the component first mounts. But if the Element doesn't exist yet, which happens when an async `stripe` prop is passed to the `<Elements>` provider, there is no Element to clean up when the component unmounts.
We tested whether the Element was destroyed in the sync case, but not in the async case. I added a test for the async case.
> Fix Element effect cleanup when using async stripe prop

- src/components/createElementComponent.test.tsx
- src/components/createElementComponent.tsx
Fixes race condition of adding and removing a card element at the same time in React 17.
https://github.com/stripe/react-stripe-js/issues/154
https://codesandbox.io/s/gracious-dawn-txrz7?file=/src/App.js
Reproduce of existing issue and tested it with fix.
> [React@17] useLayoutEffect for synchronous cleanup

- package.json
- src/index.ts
- src/types/index.ts
- yarn.lock
Added support for new `afterpayClearpayMessage` Element.
Verified that `typecheck` passes.
> Adding support for `afterpayClearpayMessage` Element

- src/components/Elements.tsx
- test/mocks.js
This PR calls `stripe.registerAppInfo` to track `react-stripe-js` usage. It is part of the workstream to track OSS library attribution.
Tested out manually
> Register library information with registerAppInfo

- package.json
- src/components/Elements.test.tsx
Fix two lint warnings and stop allowing warnings to linger. Keep that code ✨ 
Ran `yarn lint` with no errors and no warnings
> Fix lint warnings

- package.json
- yarn.lock
Update [@stripe/stripe-js](https://github.com/stripe/stripe-js) to latest version ([v1.18.0](https://github.com/stripe/stripe-js/releases/tag/v1.18.0)) so that we can add React bindings for the Payment Element and support updating options passed to the `Elements` provider.
Just a dependency version bump. Existing tests still pass.
> update to latest stripe-js version

- src/types/index.ts
Utilize and expose the types provided by `@stripe/stripe-js` for the `PaymentElement` in the `PaymentElementComponent` type.
Types only change. We don't currently have types level tests in React Stripe.js.
> utilize types for Payment element

- src/utils/extractAllowedOptionsUpdates.test.ts
- src/utils/isEqual.ts
Fixes https://github.com/stripe/react-stripe-js/issues/230.
Added test.
> Fix isEqual to work with special object.

- src/components/createElementComponent.tsx
Remove duplicate `"an"` in comments for custom `onClick` handler.
Change `// Users can pass an an onClick prop on any Element component` to `// Users can pass an onClick prop on any Element component`.
**How did you test this change?**
No testing needed. Actual code not effected.
> Friendly spellcheck in comments

- src/components/Elements.tsx
The new `@types/react@^18` package ships with [several breaking changes](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56210). One such change is that `children` prop is no longer automatically included as part of the `FunctionalComponent` (ie `FC`) typing. Components need to opt-in to the `children` prop now.
The `Elements` component uses `children` and consumers who have upgraded to `@types/react@^18` will get an error `<Element />` does not have `children`.
This change adds `children` component typing that is compatible with `@types/react@^18` changes.
---
Side note: This was originally provided by @NuroDev via #280, but the author hasn't signed the CLA and isn't responding to the request to sign the CLA. I'm submitting this fix in order to provide a fix to the community …
> fix: children prop typing on Elements component

- scripts/publish
This updates the publish script to support other yarn versioning changes: 
https://classic.yarnpkg.com/en/docs/cli/version#toc-yarn-version-premajor
e.g., `./scripts/publish preminor`
> Add support for prereleases

- src/components/Elements.test.tsx
- src/components/Elements.tsx
We've been unable to find the conditions to reproduce #296, but this should prevent the expected cause, which is unnecessary recreation of the elements group instance when the stripe promise resolves. At worst, this change does nothing.
Added a new test that simulates updating the element's option before the promise resolves.
> Prevent unnecessary recreation of elements instance

- package.json
- src/components/createElementComponent.test.tsx
- src/components/createElementComponent.tsx
- src/types/index.ts
- yarn.lock
Add support for `onLoaderStart` convenience prop to the `loaderStart` event.
This PR adds this prop to `payment`, `shippingAddress`, and `linkAuthentication` Elements.
Added test
> Add `onLoaderStart` prop

- package.json
- yarn.lock
Update @stripe/stripe-js to [v1.35.0](https://github.com/stripe/stripe-js/releases/tag/v1.35.0) for shipping address element options changes.
Existing tests still pass.
> Bump stripe-js version to 1.35.0

- .storybook/example.stories.js
- examples/hooks/10-Cart.js
- package.json
- src/components/Elements.test.tsx
- src/components/Elements.tsx
- src/components/createElementComponent.test.tsx
- src/components/createElementComponent.tsx
- src/index.ts
- src/types/index.ts
- test/mocks.js
- yarn.lock
**useCartElement**
`useCartElement` is a react hook that retrieves the Cart Element, similar to the effect of calling `elements.getElement('cart')`. This hook exists so that React users can more easily call cart functions such as:
```
const cartElement = useCartElement();
cartElement.addLineItem({product: "prod_123"});
cartElement.show();
cartElement.hide();
cartElement.cancelCheckout("Checkout cancelled because...");
cartElement.update({ showOnAdd: false );
```
**useCartElementState**
`useCartElementState` is a react hook that retrieves the last value returned by the `ready` or `change` events (or null if no event has occurred yet). This value is used to display the cart count in the merchant's UI. The value returned has the shape:
```
{
id: "cart_session_123",
elementType: 'cart', …
```
> Add useCartElement and useCartElementState hooks

- examples/hooks/10-Cart.js
- src/components/createElementComponent.tsx
Changes the onReady event handler for cart to return the event instead of the element. Returning the element is correct behavior for other elements, but the cart element needs to return the event instead.
Updated and ran storybook
> Updated cart ready event to return event instead of element

- package.json
- src/components/createElementComponent.test.tsx
- src/components/createElementComponent.tsx
- src/index.ts
- src/types/index.ts
- yarn.lock
Adds component for the `payButton` element.
Performed manual testing using a local React project.
> Add component for payButton element

- scripts/publish
Depending on one's 2FA settings with npm, the script may console output a link you need to go to to perform the auth. When the script runs with `-s`, you can't click on that link.
As a fix, this removes the `-s` flag.
Ran the command without `-s` to publish the latest version :)
> Do not run the "publishing release" script silently

- src/components/createElementComponent.test.tsx
- src/components/createElementComponent.tsx
Addresses #375: if un-mounting occurs on the same render as creating the element (ex. in strictmode), `elements.create` could get called multiple times without `element.destroy` being called. This was because setting our state with `setElement` doesn't apply to the next render, so the `element` would still be null and we wouldn't call to destroy.
This PR reverts part of #372 by switching back to a ref to track creating, updating, and destroying an element. However, it keeps the `element` state used to attach events in that PR.
- Added unit test that fails in v1.16.3 for strict mode to make sure .create() and destroy() get called correctly
- Tested against [reproduction](https://glitch.com/edit/#!/boundless-goofy-tanker?path=src%2Findex.jsx%3A18%3A8) of the issue, where multiple re-renders …
> Switch back to a ref to track element creating, updating, and destroying

- src/components/createElementComponent.tsx
When the Payment Element destroys itself, React doesn't always know about it. So when React attempts to unmount the a destroyed PE, an integration error is thrown and the application crashes.
One reproducible scenario of this is when creating a PE with an `amount` that is too small. The call to elements/session returns an error like this:
```
No valid payment method types for this configuration. Please ensure that you have activated payment methods compatible with your chosen currency in your dashboard (https://dashboard.stripe.com/settings/payment_methods) and that the `amount` (30) is not lower than the `currency` (usd) minimum: https://stripe.com/docs/currencies#minimum-and-maximum-charge-amounts
```
Then the `loaderror` event is triggered. (I believe the component self-destructs in …
> Wraps component destructor in a trycatch

- package.json
- yarn.lock
Addresses #429 
[stripe-js/compare/v1.54.2...v2.0.0](https://github.com/stripe/stripe-js/compare/v1.54.2...v2.0.0)
Tested actual checkout in my personal project without issues, however, I was not using the 'none' theme. 
Thanks
> upgrade stripe-js to 2.0.0 and peerDep

- scripts/publish
Add preid support in publish script
```shell
❯ ./scripts/publish -h        
USAGE:
./scripts/publish <release_type> <pre_id>
ARGS:
<release_type>
A Semantic Versioning release type used to bump the version number. Either "patch", "minor", "major", "prepatch", "preminor", "premajor", or "prerelease".
<pre_id>
Adds an identifier to be used to prefix premajor, preminor, prepatch or prerelease version increments. Either "alpha" or "beta".
❯ ./scripts/publish patch beta
Invalid RELEASE_TYPE. It should be one of: 'prepatch', 'preminor', 'premajor', 'prerelease',  when PREID is set
USAGE:
./scripts/publish <release_type> <pre_id>
ARGS: …
```
> Add preid support in publish script

- scripts/publish
Fix publish script. The regex comparison failed when release_type is `patch` because it sub-match `prepatch`.
Replace the logic to NOT use the 🙈 regex and use plain for-loop comparison. 😌 (❤️  Bash script!)
1. validation on preid
```shell
❯ ./scripts/publish patch x                   
Invalid pre_id. It should be either 'alpha' or 'beta'
USAGE:
./scripts/publish <release_type> <pre_id>
ARGS:
<release_type>
A Semantic Versioning release type used to bump the version number. Either "patch", "minor", "major", "prepatch", "preminor", "premajor", or "prerelease".
<pre_id>
Adds an identifier to be used to prefix premajor, preminor, prepatch or …
```
> Fix publish script

- src/components/Elements.tsx
- src/utils/parseStripeProp.ts
- src/utils/registerWithStripeJs.ts
Preparation for supporting Embedded Checkout in react-stripe-js.
We'll be using the extracted utils there -- I'm just creating a separate PR to keep the diff of the next one smaller.
Existing unit tests
> extract some utils

- .gitignore
- examples/hooks/11-Custom-Checkout.js
- package.json
- src/components/CustomCheckout.test.tsx
- src/components/CustomCheckout.tsx
- src/components/Elements.test.tsx
- src/components/Elements.tsx
- src/components/createElementComponent.test.tsx
- src/components/createElementComponent.tsx
- src/index.ts
- src/utils/parseStripeProp.ts
- test/mocks.js
- yarn.lock
This is to add `<CustomCheckoutProvider />` component.
- bump @stripe/stripe-js version (so it has types from https://github.com/stripe/stripe-js/pull/489)
- add `<CustomCheckoutProvider />`
- add storybook example
- unit test
- storybook example
https://github.com/stripe/react-stripe-js/assets/65737086/45ea276b-cc44-4b50-8d0e-e07411d3e2dd
- my own demo in next.js
https://github.com/stripe/react-stripe-js/assets/65737086/c7714b52-a169-4ab2-ace7-33bfe397006a
> Add CustomCheckoutProvider

- src/components/CustomCheckout.tsx
Throw error when CustomCheckoutContext value is null
- we don't render any children until the context is set. So as long as the app is wrapped in CustomCheckoutProvider, users should not hit this error.
- This is to make it easier for TS users to destruct the object without worrying about nullable cases
Tested in storybook
> Throw error when CustomCheckoutContext value is null

- src/components/EmbeddedCheckout.client.test.tsx
- src/components/EmbeddedCheckout.tsx
r? @tiff-stripe && @pololi-stripe 
[The cleanup order for effects in React is parent, then child.](https://github.com/facebook/react/issues/16728).
This PR makes sure that we catch the error that gets emitted when a destroyed Embedded Checkout instance gets unmounted (we do something similar for Elements).
Unit test
> Prevent Embedded Checkout unmount errors

- scripts/publish
Adds a quick 'n easy check for our publish script to see if the GITHUB_TOKEN is set.
```
GITHUB_TOKEN="" ./scripts/publish patch
GITHUB_TOKEN is not set.
```
> update publish script to check for github token

- package.json
- yarn.lock
Uses new `@stripe/stripe-js` release as a dependency. No other changes.
> Upgrade stripe-js dependency

- src/components/CustomCheckout.test.tsx
- src/components/Elements.test.tsx
- src/components/Elements.tsx
- src/components/useStripe.tsx
- src/index.ts
This change removes a cyclic dependency.
There are no API changes in this PR
Tested `useStripe()` in a local integration
> Remove cyclic dependency

- src/components/EmbeddedCheckout.client.test.tsx
- src/components/EmbeddedCheckoutProvider.test.tsx
- src/components/EmbeddedCheckoutProvider.tsx
Adds support for passing the `fetchClientSecret` param to `<EmbeddedCheckoutProvider>`'s `options` prop.
Example usage:
```javascript
import * as React from 'react';
import {loadStripe} from '@stripe/stripe-js';
import {
EmbeddedCheckoutProvider,
EmbeddedCheckout
} from '@stripe/react-stripe-js';
const stripePromise = loadStripe('pk_test_123', {betas: ['embedded_checkout_beta_1']}));
const App = ({createCheckoutSession}) => {
const options = {
fetchClientSecret: async () => { 
const clientSecret = await createCheckoutSession(); 
return clientSecret;
}
};
return (
<EmbeddedCheckoutProvider
stripe={stripePromise}
options={options}
/>
<EmbeddedCheckout />
</EmbeddedCheckoutProvider>
)
}
```
Unit tests and manual testing locally.
> Add support for fetchClientSecret param to Embedded Checkout

- .github/workflows/build.yml
- package.json
- rollup.config.js
- scripts/check-imports
- yarn.lock
In this PR we are upgrading rollup and our build configurations to the most recent / modern versions of the libraries. I will do my best to explain what has been upgraded. I've added comments inline to where the changes have been made
```
st-madhav1:react-stripe-js madhav$ npx publint
@stripe/react-stripe-js lint results:
Suggestions:
1. The package does not specify the type field. Environments may incorrectly identify a CJS file as ESM in the future. Consider adding "type": "commonjs".
2. pkg.module is used to output ESM, but pkg.exports is not defined. As NodeJS doesn't read pkg.module, the ESM output may be skipped. Consider adding pkg.exports to export the ESM output. pkg.module can usually be removed alongside too. (This will be a breaking change)
3. pkg["jsnext:main"] is deprecated. …
```
> upgrade rollup out of the stone age

- src/types/index.ts
Users will now be able to use onLoadError on the card and cardNumber elements:
```
cardElement.onLoadError((e) => console.log(e));
cardNumberElement.onLoadError((e) => console.log(e));
```
https://docs.google.com/document/d/1ZoI--5Uuiy9j_FfEJauL9i_X5vf7miEsHIOp-2JS0eY/edit
I wrote unit tests
Will update the documentation when we release the feature
> Add onLoadError to card and cardNumber elements

- .github/workflows/build.yml
- package.json
- scripts/publish
- yarn.lock
This changeset checks exported types in CI and when publishing a release version.
I ran the new package script locally, and CI passes.
This change is analagous to stripe/stripe-js#597 and stripe/stripe-js#598.
> Run @arethetypeswrong/cli in CI + before publish

- package.json
- src/components/EmbeddedCheckoutProvider.test.tsx
- src/components/EmbeddedCheckoutProvider.tsx
- yarn.lock
Update EmbeddedCheckoutProvider prop types
> Update EmbeddedCheckoutProvider prop types

- package.json
- src/components/EmbeddedCheckoutProvider.test.tsx
- src/components/EmbeddedCheckoutProvider.tsx
- yarn.lock
Add onLineItemsChange option to EmbeddedCheckoutProvider
> Add onLineItemsChange option to EmbeddedCheckoutProvider

- scripts/publish
When publishing this package, our build is run before the version bump so the output artifact's version lags behind.
This change moves the build after the version bump.
Note: the test command is still run before the version bump and should catch any immediate problems with the code.
> Fix lagging version in build

- package.json
- yarn.lock
This change updates the `@stripe/stripe-js` peer dependency in preparation for Acacia.
https://github.com/stripe/stripe-js/pull/737
Tested on https://jubianchi.github.io/semver-check
* 1.44.1: match
* 6.0.0: match
* 6.9.9: match
* 1.44.0: no match
* 7.0.0: no match
> Update @stripe/stripe-js peer dependency

- scripts/publish
This change removes the silent flag to make any issues in releases more apparent. This is how `@stripe/stripe-js` [already works](https://github.com/stripe/stripe-js/blob/master/scripts/publish#L148).
Will test in a publish after this is merged
> Remove silent flag

- package.json
- yarn.lock
Update the dependency on stripe-js to v7 and include new version in peerDependency.
> Update stripe-js dep to v7

- scripts/publish
If the publish script is run without the `dist` folder, it fails. This commit moves the test section after the build to fix this problem.
Previously, I moved the build after the version so the new version is in the output, but I did not move the test section also. This meant the tests were running on an outdated build and would fail if a build had not been run.
> Fix clean publish bug

- src/components/CheckoutProvider.tsx
This fixes an bug where Appearance API updates that get made before the Checkout SDK is ready get ignored forever.
> Fix issue with ignored appearance changes.

- src/components/Elements.tsx
Updates docs link in `Elements.tsx` to point to:
- https://docs.stripe.com/sdks/stripejs-react?ui=elements#elements-provider
> Update docs link Elements.tsx

- package.json
- src/components/CheckoutProvider.test.tsx
- src/components/CheckoutProvider.tsx
- test/mocks.js
- yarn.lock
When `elementsOptions.fonts` is updated in `CheckoutProvider`, we update Elements accordingly with any new fonts.
Internal Stripe API review.
Wrote unit tests.
> feat: load fonts when they change

- README.md
This change removes the broken Travis badge from the readme
Observed the [rendered readme](https://github.com/stripe/react-stripe-js/blob/c1fc55af33e5c20810cb38c9721833c369b92814/README.md) without the broken badge
> Remove broken Travis badge

- src/components/CheckoutProvider.test.tsx
- src/components/CheckoutProvider.tsx
- src/components/createElementComponent.test.tsx
- src/components/createElementComponent.tsx
- src/components/useStripe.tsx
- src/index.ts
- test/makeDeferred.ts
r? @pololi-stripe 
Updates `CheckoutProvider` and `useCheckout` to return a disjoint union of loading/error/success always, rather than rendering null until everything loads.
[APIREVIEW-3693](https://jira.corp.stripe.com/browse/APIREVIEW-3693)
> [breaking] Update useCheckout to return loading/error states

- checkout.d.ts
- checkout.js
- package.json
- rollup.config.js
- src/checkout/components/CheckoutProvider.test.tsx
- src/checkout/components/CheckoutProvider.tsx
- src/checkout/index.ts
- src/checkout/types/index.ts
- src/components/createElementComponent.test.tsx
- src/components/createElementComponent.tsx
- src/components/useStripe.tsx
- src/index.ts
- src/types/index.ts
Splits EwCS specific imports into its own `/checkout` path.
https://jira.corp.stripe.com/browse/APIREVIEW-3693
> [breaking] split out custom checkout imports

- package.json
- yarn.lock
Releasing react-stripe-js clover today
This PR will remain open until Stripe.js@8.0.0 is published so we can update peerDependency, devDependency, and the yarn lockfile.
> Prepare for clover release

- src/components/FinancialAccountDisclosure.test.tsx
- src/components/FinancialAccountDisclosure.tsx
Adds a new React component, `FinancialAccountDisclosure`, that users can use to add the compulsory disclosure text detailing our Financial Account (FA) for platforms product (fka Treasury), the banking partners we work with, and information about FDIC insurance.
I tested this change by creating a new local testing file in `examples/hooks` and running `yarn run storybook`
You can see the files I used to test [here](https://github.com/stripe/react-stripe-js/commit/80d8c4937bafe31eaba84779e9fc2eb507edbc7a).
I also wrote tests in `src/components/FinancialAccountDisclosure.test.tsx` that I ran with `yarn jest`
> Add Financial Account for Platforms disclosure React component
