stripe/react-stripe-js

- .github/ISSUE_TEMPLATE.md
- CONTRIBUTING.md
- README.md
- docs/migrating.md
* Add a migration guide
* Update the readme to point at the official docs
> Docs updates

- CHANGELOG.md
- README.md
* Update changelog
* Add note about beta documentation
> changelog and beta docs note

- README.md
- examples/class-components/0-Card-Minimal.js
- examples/class-components/1-Card-Detailed.js
- examples/class-components/2-Split-Card.js
- examples/class-components/3-Payment-Request-Button.js
- examples/class-components/4-IBAN.js
- examples/class-components/5-iDEAL.js
- examples/class-components/6-FPX.js
- examples/hooks/0-Card-Minimal.js
- examples/hooks/1-Card-Detailed.js
- examples/hooks/2-Split-Card.js
- examples/hooks/3-Payment-Request-Button.js
- examples/hooks/4-IBAN.js
- examples/hooks/5-iDEAL.js
- examples/hooks/6-FPX.js
Add links to integration guides in the readme and all examples.
Docs only.
> add links to integration guides

- examples/class-components/0-Card-Minimal.js
- examples/class-components/1-Card-Detailed.js
- examples/class-components/2-Split-Card.js
- examples/class-components/3-Payment-Request-Button.js
- examples/class-components/4-IBAN.js
- examples/class-components/5-iDEAL.js
- examples/class-components/6-FPX.js
- examples/hooks/0-Card-Minimal.js
- examples/hooks/1-Card-Detailed.js
- examples/hooks/2-Split-Card.js
- examples/hooks/3-Payment-Request-Button.js
- examples/hooks/4-IBAN.js
- examples/hooks/5-iDEAL.js
- examples/hooks/6-FPX.js
- src/components/Elements.tsx
- src/components/createElementComponent.test.js
Spell checks for couple of words like 
> official, satisfy, unnecessary and updatable.
> Typo fixes for examples/  and src/components/ folder

- package.json
- src/components/createElementComponent.test.js
- src/components/createElementComponent.tsx
- src/types/index.ts
- yarn.lock
Adds an `onEscape` prop to Elements.
> Add escape event props

- src/index.ts
export types.
For example, when used in a styled-component, the required `types` are not exported and cannot be built
for example 
```diff
> export { ElementProps, AuBankAccountElementProps, AuBankAccountElementComponent, CardElementProps, CardElementComponent, CardNumberElementProps, CardNumberElementComponent, CardExpiryElementProps, CardExpiryElementComponent, CardCvcElementProps, CardCvcElementComponent, FpxBankElementProps, FpxBankElementComponent, IbanElementProps, IbanElementComponent, IdealBankElementProps, IdealBankElementComponent, PaymentRequestButtonElementProps, PaymentRequestButtonElementComponent, useElements, useStripe, Elements, ElementsConsumer, AuBankAccountElement, CardElement, CardNumberElement, CardExpiryElement, CardCvcElement, FpxBankElement, IbanElement, …
```
> chore: export types

- package.json
- scripts/publish
Same as https://github.com/stripe/stripe-js/pull/46
> Add publish script

- .travis.yml
- package.json
- scripts/publish
Same changes as https://github.com/stripe/stripe-js/pull/52.
> Fix outdated version embedding

- .idea/.gitignore
- .idea/codeStyles/Project.xml
- .idea/codeStyles/codeStyleConfig.xml
- .idea/google-java-format.xml
- .idea/inspectionProfiles/Project_Default.xml
- .idea/misc.xml
- .idea/modules.xml
- .idea/react-stripe-js.iml
- .idea/vcs.xml
- examples/class-components/7-P24.js
- examples/class-components/8-EPS.js
- examples/hooks/7-P24.js
- examples/hooks/8-EPS.js
- examples/styles/common.css
- src/index.ts
- src/types/index.ts
- Add components and types for `p24Bank` and `epsBank` elements.
- Add an example for each
Manually tested examples in storyboard
> P24 and EPS Bank account elements

- src/components/createElementComponent.tsx
- src/index.ts
- src/types/index.ts
Add some placeholders for an in-development feature.
Test suite continues to pass.
> Add placeholders for `payment` Element

- .github/ISSUE_TEMPLATE.md
Replaced IRC reference with Discord in issue template
N/A
> Replaced IRC with Discord in issue template

- package.json
- src/components/createElementComponent.tsx
- src/index.ts
- src/types/index.ts
- yarn.lock
- Update stripe-js
- Add Link authentication component
- Add shipping address component
- Remove placeholder
Test suite continues to pass.
> Add Link authentication and shipping address elements

- package.json
- src/index.ts
- src/types/index.ts
- yarn.lock
Added support for new `affirmMessage` Element.
`typecheck` passes
> [Affirm] Add support for affirmMessage

- CONTRIBUTING.md
This PR updated CONTRIBUTING.md to use discord link.
> Update CONTRIBUTING.md to use discord link

- .storybook/example.stories.js
- .storybook/main.js
- README.md
- examples/class-components/1-Card-Detailed.js
- examples/hooks/1-Card-Detailed.js
- examples/hooks/9-Payment-Element.js
- examples/styles/2-Card-Detailed.css
- examples/styles/common.css
- package.json
- src/components/Elements.test.tsx
- src/components/Elements.tsx
- src/components/createElementComponent.test.tsx
- src/components/createElementComponent.tsx
- src/utils/usePrevious.test.tsx
- yarn.lock
React `StrictMode` adds additional behavior in development mode that triggers effects and lifecycle events multiple times to detect unexpected side effects:
https://reactjs.org/docs/strict-mode.html
Example behavior:
```
* React mounts the component.
* Layout effects are created.
* Effect effects are created.
* React simulates effects being destroyed on a mounted component.
* Layout effects are destroyed.
* Effects are destroyed.
* React simulates effects being re-created on a mounted component.
* Layout effects are created
* Effect setup code runs
```
This PR updates the react-stripe-js bindings to the imperative Stripe.js code to gracefully handle these simulations.
To validated this, we:
1) Upgraded Storybook and configured it to run in StrictMode
2) Added additional tests that run in …
> Support React StrictMode

- package.json
- yarn.lock
Update [@stripe/stripe-js](https://github.com/stripe/stripe-js) to latest version ([v1.31.0](https://github.com/stripe/stripe-js/releases/tag/v1.31.0)).
Just a dependency version bump. Existing tests still pass.
> update to latest stripe-js version

- package.json
- src/index.ts
- src/types/index.ts
- yarn.lock
- Updated stripe-js dependency
- Add `AddressElement` component
- Mark `ShippingAddressElement` as deprecated
Test suite continues to pass
> Add AddressElement

- package.json
- src/index.ts
- src/types/index.ts
- yarn.lock
Adds cart component to available react components
Will perform manual testing
> Added cart component

- package.json
Update to use new `stripe-js` version
Use existing tests
> Update stripe-js version

- src/index.ts
Remove beta access comment for Address Element.
Updating comments only.
> AE: Remove beta comment

- src/types/index.ts
Resolution for:
https://github.com/stripe/react-stripe-js/issues/351
https://github.com/stripe/react-stripe-js/issues/105 (previously only partly fixed)
Tested by running storybook examples in the repo
> Add type definitions for focus and blur callback

- package.json
- yarn.lock
New version of `@stripe/stripe-js` to pick up new `types` for the Payment Element.
Dependency update covered by existing tests.
> Installs the latest version of @stripe/stripe-js

- package.json
- src/components/createElementComponent.test.tsx
- src/components/createElementComponent.tsx
- src/index.ts
- src/types/index.ts
- yarn.lock
Renaming PayButtonElement to ExpressCheckoutElement. Bumps the stripe-js version.
Changed existing tests, existing tests still pass
> Rename PayButtonElement to ExpressCheckoutElement

- package.json
- yarn.lock
> bump stripe-js javascript package

- README.md
Payment Element is now the recommended path for Stripe users, update the example to use the Payment Element instead of the Card Element. The deferred intent flow is being used in the example code.
README updates only
> Update README example to use the Payment Element

- README.md
Adds a missing import dependency from the demo in the Readme 
N/A
> Adds a missing import from the README demo.

- scripts/publish
> update publish script

- src/index.ts
ECE and LAE are no longer in beta, so removing these mentions in our doc comments.
Docs edits
> Remove mentions of ECE being in beta

- examples/hooks/12-Embedded-Checkout.js
Removes the beta flag passed in to load embedded checkout as we are releasing this feature to GA. Will merge tomorrow.
n/a, change is small enough and only related a code example
> Remove beta flag for embedded checkout on stripe js example

- package.json
- yarn.lock
Dependency upgrade
Automated tests should work.
> Use @stripe/stripe-js ^3.0.9

- package.json
- yarn.lock
Update @stripe/stripe-js dev dependency
> Update @stripe/stripe-js dev dependency

- package.json
- src/components/createElementComponent.tsx
- src/index.ts
- src/types/index.ts
- yarn.lock
Adds the React support for Currency Selector Element
Tested locally, and can use the CurrencySelectorElement React component!
> Add currency selector element support

- examples/hooks/11-Custom-Checkout.js
- package.json
- src/components/CheckoutProvider.test.tsx
- src/components/CheckoutProvider.tsx
- src/components/createElementComponent.test.tsx
- src/components/createElementComponent.tsx
- test/mocks.js
- yarn.lock
Updates the React implementation for Checkout to work with the new custom_checkout_beta_6.
Added tests for error cases
> Update implementation for Elements with Checkout Session beta 6

- scripts/publish
This is the same fix done to `@stripe/stripe-js`
https://github.com/stripe/stripe-js/pull/697
Will test in a release after it is merged
> Fix publish signed commit check #697

- src/components/CheckoutProvider.tsx
useCheckout() will return the session proxy with actions added, rather than a new object.
Manual testing
> Add actions to session to preserve proxy

- src/components/CheckoutProvider.tsx
- src/index.ts
- Exporting return type `CheckoutContextValue` for the `useCheckout` hook
Tested by linking package to local react app
> Export CheckoutContextValue type for useCheckout hook

- package.json
- src/components/createElementComponent.tsx
- src/index.ts
- src/types/index.ts
- yarn.lock
- Add Tax ID Element React types
[API Review](https://docs.google.com/document/d/18KURX1GBycIJQz1GeKcJOtcpAKtYQBM-H3DqKUq-xhw/edit?usp=sharing)
> Add Tax ID Element Types
